title: Blog của Lưu
baseURL: /
params:
  favicon:
    enable: true
    path: /favicon.ico
    version: 1.0
    maskIicon: '#5bbad5'
    tileColor: '#da532c'
    themeColor: '#ffffff'
  layout_style: default
  palette: orange
  header:
    title: Phan Duy Lưu
    tagline: ''
    profile_img: /images/bcl-1024x226-1-1.png
    bg: light
    has_nav: true
    has_social: true
  footer:
    content: 'chào mừng các bạn đến với '
    links:
      - text: blog của tui <3.
        url: 'https://luublog.cf'
        new_window: true
disableKinds:
  - RSS
  # - taxonomy
  # - taxonomyTerm
enableRobotsTXT: true
removePathAccents: true
permalinks:
  post: '/bai-viet/:slug'
  tags: '/tags/:slug'
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: title
      weight: 100
    - name: body
      weight: 100
taxonomies:
  category: categories
  tag: tags
