title: Blog của Lưu
baseURL: /
params:
  layout_style: default
  palette: orange
  header:
    title: Blog của Lưu
    tagline: Phan Duy Lưu
    profile_img: /images/bcl-1024x226-1-1.png
    bg: light
    has_nav: true
    has_social: true
  footer:
    content: 'chào mừng các bạn đến với '
    links:
      - text: blog của tui <3.
        url: 'https://luublog.cf'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
